import React from 'react';
import { X, Printer, Download, CheckCircle2 } from 'lucide-react';
import { WorkerRegistration, WorkerRenewal, WorkerClaim, OfficeSettings } from '../types';
import { printFormattedElement } from '../utils/exportUtils';

interface PrintSlipModalProps {
  type: 'registration' | 'renewal' | 'claim';
  data: WorkerRegistration | WorkerRenewal | WorkerClaim | any;
  settings: OfficeSettings;
  onClose: () => void;
}

export const PrintSlipModal: React.FC<PrintSlipModalProps> = ({
  type,
  data,
  settings,
  onClose,
}) => {
  const handleTriggerPrint = () => {
    let title = '';
    let body = '';

    if (type === 'registration') {
      const reg = data as WorkerRegistration;
      title = `Worker Registration Slip - ${reg.mhNumber}`;
      body = `
        <div className="header">
          <h1>${settings.officeName}</h1>
          <p>${settings.officeAddress} • Contact: ${settings.contactNumbers}</p>
          <div className="badge">MAHARASHTRA BUILDING & OTHER CONSTRUCTION WORKERS WELFARE BOARD</div>
        </div>

        <h2 style="text-align: center; color: #0284c7; margin-bottom: 20px;">WORKER REGISTRATION IDENTITY SLIP</h2>

        <table style="width: 100%;">
          <tr>
            <th style="width: 30%;">MH Registration No</th>
            <td style="font-weight: bold; color: #0369a1; font-size: 15px;">${
              (reg.status === 'Active' || reg.appStatus === 'Accepted') && reg.mhNumber && !reg.mhNumber.startsWith('PENDING-')
                ? reg.mhNumber
                : 'Pending Verification'
            }</td>
          </tr>
          <tr>
            <th>Registration System ID</th>
            <td>${reg.id}</td>
          </tr>
          <tr>
            <th>Worker Full Name</th>
            <td style="font-weight: bold;">${reg.workerName}</td>
          </tr>
          <tr>
            <th>Father / Husband Name</th>
            <td>${reg.fatherName}</td>
          </tr>
          <tr>
            <th>DOB & Gender</th>
            <td>${reg.dob} (${reg.gender})</td>
          </tr>
          <tr>
            <th>Mobile Number</th>
            <td>${reg.mobileNumber}</td>
          </tr>
          <tr>
            <th>Aadhaar Number</th>
            <td>${reg.aadhaarNumber}</td>
          </tr>
          <tr>
            <th>Address & Location</th>
            <td>${reg.address}, ${reg.village}, Taluka: <b>${reg.taluka}</b>, District: ${reg.district} - ${reg.pincode}</td>
          </tr>
          <tr>
            <th>Bank DBT Account</th>
            <td>${reg.bankName} • A/C: <b>${reg.accountNumber}</b> (IFSC: ${reg.ifsc})</td>
          </tr>
          <tr>
            <th>Registration Date</th>
            <td>${reg.registrationDate} (Verified by: ${reg.operatorName})</td>
          </tr>
          <tr>
            <th>Fee Paid</th>
            <td>₹${reg.feePaid || 100} (Receipt Issued)</td>
          </tr>
        </table>

        <div className="footer">
          <div>
            <p>Generated by e-Seva Operator: <b>${reg.operatorName}</b></p>
            <p>System Timestamp: ${new Date().toLocaleString()}</p>
          </div>
          <div className="stamp-box">
            OFFICE SEAL / STAMP
          </div>
        </div>
      `;
    } else if (type === 'renewal') {
      const ren = data as WorkerRenewal;
      title = `Renewal Receipt - ${ren.id}`;
      body = `
        <div className="header">
          <h1>${settings.officeName}</h1>
          <p>${settings.officeAddress} • Contact: ${settings.contactNumbers}</p>
          <div className="badge">MBOCWW WORKER REGISTRATION RENEWAL SLIP</div>
        </div>

        <h2 style="text-align: center; color: #0369a1; margin-bottom: 20px;">RENEWAL RECEIPT ACKNOWLEDGEMENT</h2>

        <table>
          <tr>
            <th>Renewal Slip ID</th>
            <td><b>${ren.id}</b></td>
          </tr>
          <tr>
            <th>MH Registration Number</th>
            <td style="font-weight: bold; color: #0284c7;">${ren.mhNumber}</td>
          </tr>
          <tr>
            <th>Worker Name</th>
            <td><b>${ren.workerName}</b></td>
          </tr>
          <tr>
            <th>Renewal Period</th>
            <td><b>${ren.renewalPeriodYears} Year(s)</b></td>
          </tr>
          <tr>
            <th>New Valid Till Date</th>
            <td style="color: #059669; font-weight: bold;">${ren.validTill}</td>
          </tr>
          <tr>
            <th>Fee Paid Amount</th>
            <td><b>₹${ren.feeAmount}</b></td>
          </tr>
          <tr>
            <th>Renewal Date</th>
            <td>${ren.renewalDate}</td>
          </tr>
          <tr>
            <th>Operator</th>
            <td>${ren.operatorName}</td>
          </tr>
        </table>

        <div className="footer">
          <div>
            <p>Issued by: <b>${settings.officeName}</b></p>
          </div>
          <div className="stamp-box">AUTHORISED STAMP</div>
        </div>
      `;
    } else if (type === 'claim') {
      const clm = data as WorkerClaim;
      title = `Claim Voucher - ${clm.id}`;
      body = `
        <div className="header">
          <h1>${settings.officeName}</h1>
          <p>${settings.officeAddress}</p>
          <div className="badge">MBOCWW WELFARE SCHEME CLAIM ACKNOWLEDGEMENT VOUCHER</div>
        </div>

        <h2 style="text-align: center; color: #d97706; margin-bottom: 20px;">SCHEME DISBURSAL ACKNOWLEDGEMENT</h2>

        <table>
          <tr>
            <th>Claim ID</th>
            <td><b>${clm.id}</b></td>
          </tr>
          <tr>
            <th>Worker Name & MH No</th>
            <td><b>${clm.workerName}</b> (${clm.mhNumber})</td>
          </tr>
          <tr>
            <th>Taluka</th>
            <td>${clm.taluka}</td>
          </tr>
          <tr>
            <th>Applied Scheme 1</th>
            <td><b>${clm.scheme1Name}</b> (Amount: ₹${clm.scheme1Amount})</td>
          </tr>
          ${
            clm.scheme2Name
              ? `<tr><th>Applied Scheme 2</th><td><b>${clm.scheme2Name}</b> (Amount: ₹${clm.scheme2Amount})</td></tr>`
              : ''
          }
          <tr>
            <th>Total Sanctioned Aid</th>
            <td style="font-size: 18px; font-weight: bold; color: #d97706;">₹${clm.totalAmount.toLocaleString(
              'en-IN'
            )}</td>
          </tr>
          <tr>
            <th>Claim Status</th>
            <td style="font-weight: bold; color: #0284c7;">${clm.status}</td>
          </tr>
          <tr>
            <th>Remarks</th>
            <td>${clm.remarks || 'N/A'}</td>
          </tr>
        </table>

        <div className="footer">
          <div><p>Operator: ${clm.operatorName}</p></div>
          <div className="stamp-box">OFFICE SEAL</div>
        </div>
      `;
    }

    printFormattedElement(title, body);
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/40 backdrop-blur-md flex items-center justify-center p-4">
      <div className="bg-white border border-slate-200/90 rounded-3xl max-w-lg w-full p-6 shadow-2xl relative text-slate-900 space-y-4">
        <button
          onClick={onClose}
          className="absolute top-5 right-5 p-2 rounded-xl bg-slate-100 text-slate-500 hover:text-slate-900 border border-slate-200"
        >
          <X className="w-5 h-5" />
        </button>

        <div className="text-center space-y-1">
          <CheckCircle2 className="w-10 h-10 text-blue-700 mx-auto" />
          <h3 className="text-lg font-bold text-slate-900 capitalize">
            Print Official {type} Slip
          </h3>
          <p className="text-xs text-slate-500 font-medium">
            Formatted printable document with OM DIGITAL E-SEVA KENDRA header & verification seal
          </p>
        </div>

        {/* Card preview */}
        <div className="p-4 rounded-2xl bg-slate-50 border border-slate-200/90 space-y-2 text-xs">
          <div className="text-[10px] uppercase tracking-wider text-blue-800 font-bold">
            {settings.officeName}
          </div>
          <div className="font-bold text-slate-900 text-sm">
            {data.workerName || data.name}
          </div>
          <div className="text-slate-600 font-mono font-medium">
            {data.mhNumber ? `MH Reg: ${data.mhNumber}` : `ID: ${data.id}`}
          </div>
        </div>

        <div className="flex justify-end gap-3 pt-2">
          <button
            onClick={onClose}
            className="py-2.5 px-4 rounded-xl bg-slate-100 hover:bg-slate-200 text-slate-700 text-xs font-bold border border-slate-300"
          >
            Close
          </button>
          <button
            onClick={handleTriggerPrint}
            className="py-2.5 px-6 rounded-xl brand-gradient hover:opacity-95 text-white text-xs font-bold shadow-xs flex items-center gap-2"
          >
            <Printer className="w-4 h-4" />
            <span>Open Printable Window</span>
          </button>
        </div>
      </div>
    </div>
  );
};
